# Generated by Django 4.0.2 on 2022-02-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ['start_date']},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['storable', 'time']},
        ),
    ]
