# Generated by Django 4.0.2 on 2022-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_purchase_options_alter_rent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='storable',
            field=models.BooleanField(default=False),
        ),
    ]
