# Generated by Django 4.0.2 on 2022-02-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_student_storable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='real_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
